export {
  createPublishableClient,
  createSecretClient,
  createAnonClient,
  createServiceClient,
  type WaveSupabaseClient,
} from './client.js';
export type {
  User,
  Profile,
  Wallet,
  LinkedAccount,
  LinkedAccountProvider,
  Community,
  CommunityMember,
  CommunityPlatform,
  Quest,
  QuestCompletion,
  Transaction,
  Balance,
  GameEvent,
  Faction,
  FactionMember,
  FactionRole,
  FactionStatus,
  LeaderboardRow,
} from './types.js';
export {
  getUserByWallet,
  getProfile,
  getProfileById,
  createUserWithProfile,
  getWalletByUser,
  getWalletByAddress,
  insertWallet,
  updateProfileXp,
  linkAccount,
  getLinkedAccounts,
  getQuestById,
  getQuestBySlug,
  listActiveQuests,
  getQuestCompletions,
  hasQuestCompletion,
  recordQuestCompletion,
  getGlobalLeaderboard,
  createFaction,
  getFactionById,
  getFactionByName,
  listFactions,
  getFactionMember,
  getFactionMembers,
  addFactionMember,
  removeFactionMember,
  updateFactionMemberRole,
  getAllWallets,
  getAllLinkedDiscord,
  type LinkAccountInput,
  type RecordQuestCompletionInput,
  type CreateFactionInput,
} from './queries/index.js';
